# Generated by Django 3.1 on 2020-11-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='stand',
            field=models.TextField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='query',
            field=models.TextField(unique=True),
        ),
    ]
