# Generated by Django 3.1 on 2020-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0002_auto_20201104_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='query',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='stand',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
