# Generated by Django 3.1 on 2020-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0003_auto_20201115_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='query',
            field=models.TextField(unique=True),
        ),
    ]
