# Generated by Django 3.1 on 2021-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0005_auto_20210108_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='stand',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
