# Generated by Django 3.1 on 2021-01-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0006_auto_20210108_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='stand',
            field=models.TextField(blank=True, null=True),
        ),
    ]
