# Generated by Django 3.1 on 2021-01-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0007_auto_20210108_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='query',
            field=models.TextField(),
        ),
    ]
